// Generated by gencpp from file person_tracking/choose_targetRequest.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_CHOOSE_TARGETREQUEST_H
#define PERSON_TRACKING_MESSAGE_CHOOSE_TARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace person_tracking
{
template <class ContainerAllocator>
struct choose_targetRequest_
{
  typedef choose_targetRequest_<ContainerAllocator> Type;

  choose_targetRequest_()
    : target(0)  {
    }
  choose_targetRequest_(const ContainerAllocator& _alloc)
    : target(0)  {
  (void)_alloc;
    }



   typedef int32_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::person_tracking::choose_targetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::person_tracking::choose_targetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct choose_targetRequest_

typedef ::person_tracking::choose_targetRequest_<std::allocator<void> > choose_targetRequest;

typedef boost::shared_ptr< ::person_tracking::choose_targetRequest > choose_targetRequestPtr;
typedef boost::shared_ptr< ::person_tracking::choose_targetRequest const> choose_targetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::person_tracking::choose_targetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::person_tracking::choose_targetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::person_tracking::choose_targetRequest_<ContainerAllocator1> & lhs, const ::person_tracking::choose_targetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::person_tracking::choose_targetRequest_<ContainerAllocator1> & lhs, const ::person_tracking::choose_targetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace person_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::person_tracking::choose_targetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::choose_targetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::choose_targetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9e0e2644ef8436bb1313201f33658ce";
  }

  static const char* value(const ::person_tracking::choose_targetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9e0e2644ef8436bULL;
  static const uint64_t static_value2 = 0xb1313201f33658ceULL;
};

template<class ContainerAllocator>
struct DataType< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "person_tracking/choose_targetRequest";
  }

  static const char* value(const ::person_tracking::choose_targetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 target\n"
;
  }

  static const char* value(const ::person_tracking::choose_targetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct choose_targetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::person_tracking::choose_targetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::person_tracking::choose_targetRequest_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_CHOOSE_TARGETREQUEST_H
