// Generated by gencpp from file person_tracking/choose_target.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_CHOOSE_TARGET_H
#define PERSON_TRACKING_MESSAGE_CHOOSE_TARGET_H

#include <ros/service_traits.h>


#include <person_tracking/choose_targetRequest.h>
#include <person_tracking/choose_targetResponse.h>


namespace person_tracking
{

struct choose_target
{

typedef choose_targetRequest Request;
typedef choose_targetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct choose_target
} // namespace person_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::person_tracking::choose_target > {
  static const char* value()
  {
    return "02caa2968e58f6cef6489327a5fdc1c4";
  }

  static const char* value(const ::person_tracking::choose_target&) { return value(); }
};

template<>
struct DataType< ::person_tracking::choose_target > {
  static const char* value()
  {
    return "person_tracking/choose_target";
  }

  static const char* value(const ::person_tracking::choose_target&) { return value(); }
};


// service_traits::MD5Sum< ::person_tracking::choose_targetRequest> should match
// service_traits::MD5Sum< ::person_tracking::choose_target >
template<>
struct MD5Sum< ::person_tracking::choose_targetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::choose_target >::value();
  }
  static const char* value(const ::person_tracking::choose_targetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::choose_targetRequest> should match
// service_traits::DataType< ::person_tracking::choose_target >
template<>
struct DataType< ::person_tracking::choose_targetRequest>
{
  static const char* value()
  {
    return DataType< ::person_tracking::choose_target >::value();
  }
  static const char* value(const ::person_tracking::choose_targetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::person_tracking::choose_targetResponse> should match
// service_traits::MD5Sum< ::person_tracking::choose_target >
template<>
struct MD5Sum< ::person_tracking::choose_targetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::choose_target >::value();
  }
  static const char* value(const ::person_tracking::choose_targetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::choose_targetResponse> should match
// service_traits::DataType< ::person_tracking::choose_target >
template<>
struct DataType< ::person_tracking::choose_targetResponse>
{
  static const char* value()
  {
    return DataType< ::person_tracking::choose_target >::value();
  }
  static const char* value(const ::person_tracking::choose_targetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_CHOOSE_TARGET_H
