// Generated by gencpp from file person_tracking/clear_targetResponse.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_CLEAR_TARGETRESPONSE_H
#define PERSON_TRACKING_MESSAGE_CLEAR_TARGETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace person_tracking
{
template <class ContainerAllocator>
struct clear_targetResponse_
{
  typedef clear_targetResponse_<ContainerAllocator> Type;

  clear_targetResponse_()
    : success(false)  {
    }
  clear_targetResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::person_tracking::clear_targetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::person_tracking::clear_targetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct clear_targetResponse_

typedef ::person_tracking::clear_targetResponse_<std::allocator<void> > clear_targetResponse;

typedef boost::shared_ptr< ::person_tracking::clear_targetResponse > clear_targetResponsePtr;
typedef boost::shared_ptr< ::person_tracking::clear_targetResponse const> clear_targetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::person_tracking::clear_targetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::person_tracking::clear_targetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::person_tracking::clear_targetResponse_<ContainerAllocator1> & lhs, const ::person_tracking::clear_targetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::person_tracking::clear_targetResponse_<ContainerAllocator1> & lhs, const ::person_tracking::clear_targetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace person_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::person_tracking::clear_targetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::clear_targetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::clear_targetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::person_tracking::clear_targetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "person_tracking/clear_targetResponse";
  }

  static const char* value(const ::person_tracking::clear_targetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::person_tracking::clear_targetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clear_targetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::person_tracking::clear_targetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::person_tracking::clear_targetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_CLEAR_TARGETRESPONSE_H
