// Generated by gencpp from file person_tracking/clear_targetRequest.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_CLEAR_TARGETREQUEST_H
#define PERSON_TRACKING_MESSAGE_CLEAR_TARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace person_tracking
{
template <class ContainerAllocator>
struct clear_targetRequest_
{
  typedef clear_targetRequest_<ContainerAllocator> Type;

  clear_targetRequest_()
    : clear(false)  {
    }
  clear_targetRequest_(const ContainerAllocator& _alloc)
    : clear(false)  {
  (void)_alloc;
    }



   typedef uint8_t _clear_type;
  _clear_type clear;





  typedef boost::shared_ptr< ::person_tracking::clear_targetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::person_tracking::clear_targetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct clear_targetRequest_

typedef ::person_tracking::clear_targetRequest_<std::allocator<void> > clear_targetRequest;

typedef boost::shared_ptr< ::person_tracking::clear_targetRequest > clear_targetRequestPtr;
typedef boost::shared_ptr< ::person_tracking::clear_targetRequest const> clear_targetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::person_tracking::clear_targetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::person_tracking::clear_targetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::person_tracking::clear_targetRequest_<ContainerAllocator1> & lhs, const ::person_tracking::clear_targetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.clear == rhs.clear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::person_tracking::clear_targetRequest_<ContainerAllocator1> & lhs, const ::person_tracking::clear_targetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace person_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::person_tracking::clear_targetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::clear_targetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::clear_targetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f13874ec47789a29a9f87f75379435d";
  }

  static const char* value(const ::person_tracking::clear_targetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f13874ec47789a2ULL;
  static const uint64_t static_value2 = 0x9a9f87f75379435dULL;
};

template<class ContainerAllocator>
struct DataType< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "person_tracking/clear_targetRequest";
  }

  static const char* value(const ::person_tracking::clear_targetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool clear\n"
;
  }

  static const char* value(const ::person_tracking::clear_targetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clear_targetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::person_tracking::clear_targetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::person_tracking::clear_targetRequest_<ContainerAllocator>& v)
  {
    s << indent << "clear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_CLEAR_TARGETREQUEST_H
