// Generated by gencpp from file person_tracking/clear_target.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_CLEAR_TARGET_H
#define PERSON_TRACKING_MESSAGE_CLEAR_TARGET_H

#include <ros/service_traits.h>


#include <person_tracking/clear_targetRequest.h>
#include <person_tracking/clear_targetResponse.h>


namespace person_tracking
{

struct clear_target
{

typedef clear_targetRequest Request;
typedef clear_targetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct clear_target
} // namespace person_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::person_tracking::clear_target > {
  static const char* value()
  {
    return "8d891785a3ff0d216ac0e1514a9a3432";
  }

  static const char* value(const ::person_tracking::clear_target&) { return value(); }
};

template<>
struct DataType< ::person_tracking::clear_target > {
  static const char* value()
  {
    return "person_tracking/clear_target";
  }

  static const char* value(const ::person_tracking::clear_target&) { return value(); }
};


// service_traits::MD5Sum< ::person_tracking::clear_targetRequest> should match
// service_traits::MD5Sum< ::person_tracking::clear_target >
template<>
struct MD5Sum< ::person_tracking::clear_targetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::clear_target >::value();
  }
  static const char* value(const ::person_tracking::clear_targetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::clear_targetRequest> should match
// service_traits::DataType< ::person_tracking::clear_target >
template<>
struct DataType< ::person_tracking::clear_targetRequest>
{
  static const char* value()
  {
    return DataType< ::person_tracking::clear_target >::value();
  }
  static const char* value(const ::person_tracking::clear_targetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::person_tracking::clear_targetResponse> should match
// service_traits::MD5Sum< ::person_tracking::clear_target >
template<>
struct MD5Sum< ::person_tracking::clear_targetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::clear_target >::value();
  }
  static const char* value(const ::person_tracking::clear_targetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::clear_targetResponse> should match
// service_traits::DataType< ::person_tracking::clear_target >
template<>
struct DataType< ::person_tracking::clear_targetResponse>
{
  static const char* value()
  {
    return DataType< ::person_tracking::clear_target >::value();
  }
  static const char* value(const ::person_tracking::clear_targetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_CLEAR_TARGET_H
