// Generated by gencpp from file person_tracking/update_trackerResponse.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_UPDATE_TRACKERRESPONSE_H
#define PERSON_TRACKING_MESSAGE_UPDATE_TRACKERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace person_tracking
{
template <class ContainerAllocator>
struct update_trackerResponse_
{
  typedef update_trackerResponse_<ContainerAllocator> Type;

  update_trackerResponse_()
    : coordinates()  {
    }
  update_trackerResponse_(const ContainerAllocator& _alloc)
    : coordinates(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _coordinates_type;
  _coordinates_type coordinates;





  typedef boost::shared_ptr< ::person_tracking::update_trackerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::person_tracking::update_trackerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct update_trackerResponse_

typedef ::person_tracking::update_trackerResponse_<std::allocator<void> > update_trackerResponse;

typedef boost::shared_ptr< ::person_tracking::update_trackerResponse > update_trackerResponsePtr;
typedef boost::shared_ptr< ::person_tracking::update_trackerResponse const> update_trackerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::person_tracking::update_trackerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::person_tracking::update_trackerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::person_tracking::update_trackerResponse_<ContainerAllocator1> & lhs, const ::person_tracking::update_trackerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.coordinates == rhs.coordinates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::person_tracking::update_trackerResponse_<ContainerAllocator1> & lhs, const ::person_tracking::update_trackerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace person_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::person_tracking::update_trackerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::person_tracking::update_trackerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::person_tracking::update_trackerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5850328c4be1cfc40d068810a54cfe4d";
  }

  static const char* value(const ::person_tracking::update_trackerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5850328c4be1cfc4ULL;
  static const uint64_t static_value2 = 0x0d068810a54cfe4dULL;
};

template<class ContainerAllocator>
struct DataType< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "person_tracking/update_trackerResponse";
  }

  static const char* value(const ::person_tracking::update_trackerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point coordinates\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::person_tracking::update_trackerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct update_trackerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::person_tracking::update_trackerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::person_tracking::update_trackerResponse_<ContainerAllocator>& v)
  {
    s << indent << "coordinates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.coordinates);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_UPDATE_TRACKERRESPONSE_H
