// Generated by gencpp from file person_tracking/update_tracker.msg
// DO NOT EDIT!


#ifndef PERSON_TRACKING_MESSAGE_UPDATE_TRACKER_H
#define PERSON_TRACKING_MESSAGE_UPDATE_TRACKER_H

#include <ros/service_traits.h>


#include <person_tracking/update_trackerRequest.h>
#include <person_tracking/update_trackerResponse.h>


namespace person_tracking
{

struct update_tracker
{

typedef update_trackerRequest Request;
typedef update_trackerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct update_tracker
} // namespace person_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::person_tracking::update_tracker > {
  static const char* value()
  {
    return "4a50c39106e487c8fc1d6f02a4dd5e96";
  }

  static const char* value(const ::person_tracking::update_tracker&) { return value(); }
};

template<>
struct DataType< ::person_tracking::update_tracker > {
  static const char* value()
  {
    return "person_tracking/update_tracker";
  }

  static const char* value(const ::person_tracking::update_tracker&) { return value(); }
};


// service_traits::MD5Sum< ::person_tracking::update_trackerRequest> should match
// service_traits::MD5Sum< ::person_tracking::update_tracker >
template<>
struct MD5Sum< ::person_tracking::update_trackerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::update_tracker >::value();
  }
  static const char* value(const ::person_tracking::update_trackerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::update_trackerRequest> should match
// service_traits::DataType< ::person_tracking::update_tracker >
template<>
struct DataType< ::person_tracking::update_trackerRequest>
{
  static const char* value()
  {
    return DataType< ::person_tracking::update_tracker >::value();
  }
  static const char* value(const ::person_tracking::update_trackerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::person_tracking::update_trackerResponse> should match
// service_traits::MD5Sum< ::person_tracking::update_tracker >
template<>
struct MD5Sum< ::person_tracking::update_trackerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::person_tracking::update_tracker >::value();
  }
  static const char* value(const ::person_tracking::update_trackerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_tracking::update_trackerResponse> should match
// service_traits::DataType< ::person_tracking::update_tracker >
template<>
struct DataType< ::person_tracking::update_trackerResponse>
{
  static const char* value()
  {
    return DataType< ::person_tracking::update_tracker >::value();
  }
  static const char* value(const ::person_tracking::update_trackerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERSON_TRACKING_MESSAGE_UPDATE_TRACKER_H
