# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_person/PersonSkeleton.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import realsense_person.msg

class PersonSkeleton(genpy.Message):
  _md5sum = "830cfdb700931a76a5884c7211cc3672"
  _type = "realsense_person/PersonSkeleton"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string joint_type
realsense_person/RegisteredPoint skeleton_point


================================================================================
MSG: realsense_person/RegisteredPoint
geometry_msgs/Point world
int32 world_confidence
geometry_msgs/Point image
int32 image_confidence
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['joint_type','skeleton_point']
  _slot_types = ['string','realsense_person/RegisteredPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint_type,skeleton_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PersonSkeleton, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint_type is None:
        self.joint_type = ''
      if self.skeleton_point is None:
        self.skeleton_point = realsense_person.msg.RegisteredPoint()
    else:
      self.joint_type = ''
      self.skeleton_point = realsense_person.msg.RegisteredPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.joint_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3di3di().pack(_x.skeleton_point.world.x, _x.skeleton_point.world.y, _x.skeleton_point.world.z, _x.skeleton_point.world_confidence, _x.skeleton_point.image.x, _x.skeleton_point.image.y, _x.skeleton_point.image.z, _x.skeleton_point.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.skeleton_point is None:
        self.skeleton_point = realsense_person.msg.RegisteredPoint()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.joint_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.joint_type = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.skeleton_point.world.x, _x.skeleton_point.world.y, _x.skeleton_point.world.z, _x.skeleton_point.world_confidence, _x.skeleton_point.image.x, _x.skeleton_point.image.y, _x.skeleton_point.image.z, _x.skeleton_point.image_confidence,) = _get_struct_3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.joint_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3di3di().pack(_x.skeleton_point.world.x, _x.skeleton_point.world.y, _x.skeleton_point.world.z, _x.skeleton_point.world_confidence, _x.skeleton_point.image.x, _x.skeleton_point.image.y, _x.skeleton_point.image.z, _x.skeleton_point.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.skeleton_point is None:
        self.skeleton_point = realsense_person.msg.RegisteredPoint()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.joint_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.joint_type = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.skeleton_point.world.x, _x.skeleton_point.world.y, _x.skeleton_point.world.z, _x.skeleton_point.world_confidence, _x.skeleton_point.image.x, _x.skeleton_point.image.y, _x.skeleton_point.image.z, _x.skeleton_point.image_confidence,) = _get_struct_3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3di3di = None
def _get_struct_3di3di():
    global _struct_3di3di
    if _struct_3di3di is None:
        _struct_3di3di = struct.Struct("<3di3di")
    return _struct_3di3di
