# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_person/Person.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import realsense_person.msg

class Person(genpy.Message):
  _md5sum = "6933144e4378998756b146a1cd151c9e"
  _type = "realsense_person/Person"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """realsense_person/PersonId person_id
realsense_person/BoundingBox bounding_box
realsense_person/RegisteredPoint center_of_mass
================================================================================
MSG: realsense_person/PersonId
uint32 tracking_id
int32 recognition_id         #currently not populated.
string recognition_name      #placeholder in case application associates a name to the recognition_id. 
================================================================================
MSG: realsense_person/BoundingBox
int32 x
int32 y
int32 w #width of the box
int32 h #height of the box
int32 confidence

================================================================================
MSG: realsense_person/RegisteredPoint
geometry_msgs/Point world
int32 world_confidence
geometry_msgs/Point image
int32 image_confidence
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['person_id','bounding_box','center_of_mass']
  _slot_types = ['realsense_person/PersonId','realsense_person/BoundingBox','realsense_person/RegisteredPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       person_id,bounding_box,center_of_mass

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Person, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.person_id is None:
        self.person_id = realsense_person.msg.PersonId()
      if self.bounding_box is None:
        self.bounding_box = realsense_person.msg.BoundingBox()
      if self.center_of_mass is None:
        self.center_of_mass = realsense_person.msg.RegisteredPoint()
    else:
      self.person_id = realsense_person.msg.PersonId()
      self.bounding_box = realsense_person.msg.BoundingBox()
      self.center_of_mass = realsense_person.msg.RegisteredPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Ii().pack(_x.person_id.tracking_id, _x.person_id.recognition_id))
      _x = self.person_id.recognition_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5i3di3di().pack(_x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.w, _x.bounding_box.h, _x.bounding_box.confidence, _x.center_of_mass.world.x, _x.center_of_mass.world.y, _x.center_of_mass.world.z, _x.center_of_mass.world_confidence, _x.center_of_mass.image.x, _x.center_of_mass.image.y, _x.center_of_mass.image.z, _x.center_of_mass.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.person_id is None:
        self.person_id = realsense_person.msg.PersonId()
      if self.bounding_box is None:
        self.bounding_box = realsense_person.msg.BoundingBox()
      if self.center_of_mass is None:
        self.center_of_mass = realsense_person.msg.RegisteredPoint()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.person_id.tracking_id, _x.person_id.recognition_id,) = _get_struct_Ii().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person_id.recognition_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.person_id.recognition_name = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.w, _x.bounding_box.h, _x.bounding_box.confidence, _x.center_of_mass.world.x, _x.center_of_mass.world.y, _x.center_of_mass.world.z, _x.center_of_mass.world_confidence, _x.center_of_mass.image.x, _x.center_of_mass.image.y, _x.center_of_mass.image.z, _x.center_of_mass.image_confidence,) = _get_struct_5i3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Ii().pack(_x.person_id.tracking_id, _x.person_id.recognition_id))
      _x = self.person_id.recognition_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5i3di3di().pack(_x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.w, _x.bounding_box.h, _x.bounding_box.confidence, _x.center_of_mass.world.x, _x.center_of_mass.world.y, _x.center_of_mass.world.z, _x.center_of_mass.world_confidence, _x.center_of_mass.image.x, _x.center_of_mass.image.y, _x.center_of_mass.image.z, _x.center_of_mass.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.person_id is None:
        self.person_id = realsense_person.msg.PersonId()
      if self.bounding_box is None:
        self.bounding_box = realsense_person.msg.BoundingBox()
      if self.center_of_mass is None:
        self.center_of_mass = realsense_person.msg.RegisteredPoint()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.person_id.tracking_id, _x.person_id.recognition_id,) = _get_struct_Ii().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person_id.recognition_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.person_id.recognition_name = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.w, _x.bounding_box.h, _x.bounding_box.confidence, _x.center_of_mass.world.x, _x.center_of_mass.world.y, _x.center_of_mass.world.z, _x.center_of_mass.world_confidence, _x.center_of_mass.image.x, _x.center_of_mass.image.y, _x.center_of_mass.image.z, _x.center_of_mass.image_confidence,) = _get_struct_5i3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i3di3di = None
def _get_struct_5i3di3di():
    global _struct_5i3di3di
    if _struct_5i3di3di is None:
        _struct_5i3di3di = struct.Struct("<5i3di3di")
    return _struct_5i3di3di
_struct_Ii = None
def _get_struct_Ii():
    global _struct_Ii
    if _struct_Ii is None:
        _struct_Ii = struct.Struct("<Ii")
    return _struct_Ii
