# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_person/RegisteredPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class RegisteredPoint(genpy.Message):
  _md5sum = "377e1b201e51fdf9a771993c3be57884"
  _type = "realsense_person/RegisteredPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point world
int32 world_confidence
geometry_msgs/Point image
int32 image_confidence
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['world','world_confidence','image','image_confidence']
  _slot_types = ['geometry_msgs/Point','int32','geometry_msgs/Point','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       world,world_confidence,image,image_confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RegisteredPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.world is None:
        self.world = geometry_msgs.msg.Point()
      if self.world_confidence is None:
        self.world_confidence = 0
      if self.image is None:
        self.image = geometry_msgs.msg.Point()
      if self.image_confidence is None:
        self.image_confidence = 0
    else:
      self.world = geometry_msgs.msg.Point()
      self.world_confidence = 0
      self.image = geometry_msgs.msg.Point()
      self.image_confidence = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3di3di().pack(_x.world.x, _x.world.y, _x.world.z, _x.world_confidence, _x.image.x, _x.image.y, _x.image.z, _x.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.world is None:
        self.world = geometry_msgs.msg.Point()
      if self.image is None:
        self.image = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.world.x, _x.world.y, _x.world.z, _x.world_confidence, _x.image.x, _x.image.y, _x.image.z, _x.image_confidence,) = _get_struct_3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3di3di().pack(_x.world.x, _x.world.y, _x.world.z, _x.world_confidence, _x.image.x, _x.image.y, _x.image.z, _x.image_confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.world is None:
        self.world = geometry_msgs.msg.Point()
      if self.image is None:
        self.image = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.world.x, _x.world.y, _x.world.z, _x.world_confidence, _x.image.x, _x.image.y, _x.image.z, _x.image_confidence,) = _get_struct_3di3di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3di3di = None
def _get_struct_3di3di():
    global _struct_3di3di
    if _struct_3di3di is None:
        _struct_3di3di = struct.Struct("<3di3di")
    return _struct_3di3di
