// Generated by gencpp from file motpy_ros/motpy_bbox.msg
// DO NOT EDIT!


#ifndef MOTPY_ROS_MESSAGE_MOTPY_BBOX_H
#define MOTPY_ROS_MESSAGE_MOTPY_BBOX_H

#include <ros/service_traits.h>


#include <motpy_ros/motpy_bboxRequest.h>
#include <motpy_ros/motpy_bboxResponse.h>


namespace motpy_ros
{

struct motpy_bbox
{

typedef motpy_bboxRequest Request;
typedef motpy_bboxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motpy_bbox
} // namespace motpy_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motpy_ros::motpy_bbox > {
  static const char* value()
  {
    return "65b9571f1ed7828d4fcc56bef7d7664b";
  }

  static const char* value(const ::motpy_ros::motpy_bbox&) { return value(); }
};

template<>
struct DataType< ::motpy_ros::motpy_bbox > {
  static const char* value()
  {
    return "motpy_ros/motpy_bbox";
  }

  static const char* value(const ::motpy_ros::motpy_bbox&) { return value(); }
};


// service_traits::MD5Sum< ::motpy_ros::motpy_bboxRequest> should match
// service_traits::MD5Sum< ::motpy_ros::motpy_bbox >
template<>
struct MD5Sum< ::motpy_ros::motpy_bboxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motpy_ros::motpy_bbox >::value();
  }
  static const char* value(const ::motpy_ros::motpy_bboxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motpy_ros::motpy_bboxRequest> should match
// service_traits::DataType< ::motpy_ros::motpy_bbox >
template<>
struct DataType< ::motpy_ros::motpy_bboxRequest>
{
  static const char* value()
  {
    return DataType< ::motpy_ros::motpy_bbox >::value();
  }
  static const char* value(const ::motpy_ros::motpy_bboxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motpy_ros::motpy_bboxResponse> should match
// service_traits::MD5Sum< ::motpy_ros::motpy_bbox >
template<>
struct MD5Sum< ::motpy_ros::motpy_bboxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motpy_ros::motpy_bbox >::value();
  }
  static const char* value(const ::motpy_ros::motpy_bboxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motpy_ros::motpy_bboxResponse> should match
// service_traits::DataType< ::motpy_ros::motpy_bbox >
template<>
struct DataType< ::motpy_ros::motpy_bboxResponse>
{
  static const char* value()
  {
    return DataType< ::motpy_ros::motpy_bbox >::value();
  }
  static const char* value(const ::motpy_ros::motpy_bboxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTPY_ROS_MESSAGE_MOTPY_BBOX_H
