(cl:defpackage person_tracking-srv
  (:use )
  (:export
   "CHOOSE_TARGET"
   "<CHOOSE_TARGET-REQUEST>"
   "CHOOSE_TARGET-REQUEST"
   "<CHOOSE_TARGET-RESPONSE>"
   "CHOOSE_TARGET-RESPONSE"
   "CLEAR_TARGET"
   "<CLEAR_TARGET-REQUEST>"
   "CLEAR_TARGET-REQUEST"
   "<CLEAR_TARGET-RESPONSE>"
   "CLEAR_TARGET-RESPONSE"
   "UPDATE_TRACKER"
   "<UPDATE_TRACKER-REQUEST>"
   "UPDATE_TRACKER-REQUEST"
   "<UPDATE_TRACKER-RESPONSE>"
   "UPDATE_TRACKER-RESPONSE"
  ))

