// Generated by gencpp from file realsense_person/Deserialize.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_DESERIALIZE_H
#define REALSENSE_PERSON_MESSAGE_DESERIALIZE_H

#include <ros/service_traits.h>


#include <realsense_person/DeserializeRequest.h>
#include <realsense_person/DeserializeResponse.h>


namespace realsense_person
{

struct Deserialize
{

typedef DeserializeRequest Request;
typedef DeserializeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Deserialize
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::Deserialize > {
  static const char* value()
  {
    return "494333eb6aca57aeb8eaa1906a3508ec";
  }

  static const char* value(const ::realsense_person::Deserialize&) { return value(); }
};

template<>
struct DataType< ::realsense_person::Deserialize > {
  static const char* value()
  {
    return "realsense_person/Deserialize";
  }

  static const char* value(const ::realsense_person::Deserialize&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::DeserializeRequest> should match
// service_traits::MD5Sum< ::realsense_person::Deserialize >
template<>
struct MD5Sum< ::realsense_person::DeserializeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Deserialize >::value();
  }
  static const char* value(const ::realsense_person::DeserializeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::DeserializeRequest> should match
// service_traits::DataType< ::realsense_person::Deserialize >
template<>
struct DataType< ::realsense_person::DeserializeRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Deserialize >::value();
  }
  static const char* value(const ::realsense_person::DeserializeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::DeserializeResponse> should match
// service_traits::MD5Sum< ::realsense_person::Deserialize >
template<>
struct MD5Sum< ::realsense_person::DeserializeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Deserialize >::value();
  }
  static const char* value(const ::realsense_person::DeserializeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::DeserializeResponse> should match
// service_traits::DataType< ::realsense_person::Deserialize >
template<>
struct DataType< ::realsense_person::DeserializeResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Deserialize >::value();
  }
  static const char* value(const ::realsense_person::DeserializeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_DESERIALIZE_H
