// Generated by gencpp from file realsense_person/DeserializeResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_DESERIALIZERESPONSE_H
#define REALSENSE_PERSON_MESSAGE_DESERIALIZERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_person
{
template <class ContainerAllocator>
struct DeserializeResponse_
{
  typedef DeserializeResponse_<ContainerAllocator> Type;

  DeserializeResponse_()
    : success(false)  {
    }
  DeserializeResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::realsense_person::DeserializeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_person::DeserializeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeserializeResponse_

typedef ::realsense_person::DeserializeResponse_<std::allocator<void> > DeserializeResponse;

typedef boost::shared_ptr< ::realsense_person::DeserializeResponse > DeserializeResponsePtr;
typedef boost::shared_ptr< ::realsense_person::DeserializeResponse const> DeserializeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_person::DeserializeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_person::DeserializeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_person::DeserializeResponse_<ContainerAllocator1> & lhs, const ::realsense_person::DeserializeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_person::DeserializeResponse_<ContainerAllocator1> & lhs, const ::realsense_person::DeserializeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_person::DeserializeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::DeserializeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::DeserializeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::realsense_person::DeserializeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_person/DeserializeResponse";
  }

  static const char* value(const ::realsense_person::DeserializeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::realsense_person::DeserializeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeserializeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_person::DeserializeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_person::DeserializeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_DESERIALIZERESPONSE_H
