// Generated by gencpp from file realsense_person/GetTrackingId.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_GETTRACKINGID_H
#define REALSENSE_PERSON_MESSAGE_GETTRACKINGID_H

#include <ros/service_traits.h>


#include <realsense_person/GetTrackingIdRequest.h>
#include <realsense_person/GetTrackingIdResponse.h>


namespace realsense_person
{

struct GetTrackingId
{

typedef GetTrackingIdRequest Request;
typedef GetTrackingIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrackingId
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::GetTrackingId > {
  static const char* value()
  {
    return "20a696d550f9aee4109fc97b5b8cd0b7";
  }

  static const char* value(const ::realsense_person::GetTrackingId&) { return value(); }
};

template<>
struct DataType< ::realsense_person::GetTrackingId > {
  static const char* value()
  {
    return "realsense_person/GetTrackingId";
  }

  static const char* value(const ::realsense_person::GetTrackingId&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::GetTrackingIdRequest> should match
// service_traits::MD5Sum< ::realsense_person::GetTrackingId >
template<>
struct MD5Sum< ::realsense_person::GetTrackingIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::GetTrackingId >::value();
  }
  static const char* value(const ::realsense_person::GetTrackingIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::GetTrackingIdRequest> should match
// service_traits::DataType< ::realsense_person::GetTrackingId >
template<>
struct DataType< ::realsense_person::GetTrackingIdRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::GetTrackingId >::value();
  }
  static const char* value(const ::realsense_person::GetTrackingIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::GetTrackingIdResponse> should match
// service_traits::MD5Sum< ::realsense_person::GetTrackingId >
template<>
struct MD5Sum< ::realsense_person::GetTrackingIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::GetTrackingId >::value();
  }
  static const char* value(const ::realsense_person::GetTrackingIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::GetTrackingIdResponse> should match
// service_traits::DataType< ::realsense_person::GetTrackingId >
template<>
struct DataType< ::realsense_person::GetTrackingIdResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::GetTrackingId >::value();
  }
  static const char* value(const ::realsense_person::GetTrackingIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_GETTRACKINGID_H
