// Generated by gencpp from file realsense_person/PersonTracking.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_PERSONTRACKING_H
#define REALSENSE_PERSON_MESSAGE_PERSONTRACKING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <realsense_person/Person.h>
#include <realsense_person/PersonFace.h>
#include <realsense_person/PersonBody.h>

namespace realsense_person
{
template <class ContainerAllocator>
struct PersonTracking_
{
  typedef PersonTracking_<ContainerAllocator> Type;

  PersonTracking_()
    : header()
    , person()
    , person_face()
    , person_body()  {
    }
  PersonTracking_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , person(_alloc)
    , person_face(_alloc)
    , person_body(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::realsense_person::Person_<ContainerAllocator>  _person_type;
  _person_type person;

   typedef  ::realsense_person::PersonFace_<ContainerAllocator>  _person_face_type;
  _person_face_type person_face;

   typedef  ::realsense_person::PersonBody_<ContainerAllocator>  _person_body_type;
  _person_body_type person_body;





  typedef boost::shared_ptr< ::realsense_person::PersonTracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_person::PersonTracking_<ContainerAllocator> const> ConstPtr;

}; // struct PersonTracking_

typedef ::realsense_person::PersonTracking_<std::allocator<void> > PersonTracking;

typedef boost::shared_ptr< ::realsense_person::PersonTracking > PersonTrackingPtr;
typedef boost::shared_ptr< ::realsense_person::PersonTracking const> PersonTrackingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_person::PersonTracking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_person::PersonTracking_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_person::PersonTracking_<ContainerAllocator1> & lhs, const ::realsense_person::PersonTracking_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.person == rhs.person &&
    lhs.person_face == rhs.person_face &&
    lhs.person_body == rhs.person_body;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_person::PersonTracking_<ContainerAllocator1> & lhs, const ::realsense_person::PersonTracking_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_person::PersonTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_person::PersonTracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::PersonTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::PersonTracking_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::PersonTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::PersonTracking_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_person::PersonTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd4b605d2e359f7a66aec70c6f928898";
  }

  static const char* value(const ::realsense_person::PersonTracking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd4b605d2e359f7aULL;
  static const uint64_t static_value2 = 0x66aec70c6f928898ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_person::PersonTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_person/PersonTracking";
  }

  static const char* value(const ::realsense_person::PersonTracking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_person::PersonTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"realsense_person/Person person\n"
"realsense_person/PersonFace person_face\n"
"realsense_person/PersonBody person_body\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: realsense_person/Person\n"
"realsense_person/PersonId person_id\n"
"realsense_person/BoundingBox bounding_box\n"
"realsense_person/RegisteredPoint center_of_mass\n"
"================================================================================\n"
"MSG: realsense_person/PersonId\n"
"uint32 tracking_id\n"
"int32 recognition_id         #currently not populated.\n"
"string recognition_name      #placeholder in case application associates a name to the recognition_id. \n"
"================================================================================\n"
"MSG: realsense_person/BoundingBox\n"
"int32 x\n"
"int32 y\n"
"int32 w #width of the box\n"
"int32 h #height of the box\n"
"int32 confidence\n"
"\n"
"================================================================================\n"
"MSG: realsense_person/RegisteredPoint\n"
"geometry_msgs/Point world\n"
"int32 world_confidence\n"
"geometry_msgs/Point image\n"
"int32 image_confidence\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: realsense_person/PersonFace\n"
"string orientation\n"
"int32 orientation_confidence\n"
"realsense_person/BoundingBox head_bounding_box\n"
"geometry_msgs/Point head_pose                         #head_pose.x = pitch, head_pose.y = roll, head_pose.z = yaw\n"
"realsense_person/RegisteredPoint[] landmarks\n"
"int32 landmarks_confidence\n"
"\n"
"================================================================================\n"
"MSG: realsense_person/PersonBody\n"
"realsense_person/PersonSkeleton[] skeleton\n"
"realsense_person/RegisteredPoint gesture_origin\n"
"realsense_person/RegisteredPoint gesture_direction\n"
"int32 gesture_confidence\n"
"\n"
"\n"
"================================================================================\n"
"MSG: realsense_person/PersonSkeleton\n"
"string joint_type\n"
"realsense_person/RegisteredPoint skeleton_point\n"
"\n"
;
  }

  static const char* value(const ::realsense_person::PersonTracking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_person::PersonTracking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.person);
      stream.next(m.person_face);
      stream.next(m.person_body);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonTracking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_person::PersonTracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_person::PersonTracking_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "person: ";
    s << std::endl;
    Printer< ::realsense_person::Person_<ContainerAllocator> >::stream(s, indent + "  ", v.person);
    s << indent << "person_face: ";
    s << std::endl;
    Printer< ::realsense_person::PersonFace_<ContainerAllocator> >::stream(s, indent + "  ", v.person_face);
    s << indent << "person_body: ";
    s << std::endl;
    Printer< ::realsense_person::PersonBody_<ContainerAllocator> >::stream(s, indent + "  ", v.person_body);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_PERSONTRACKING_H
