// Generated by gencpp from file realsense_person/Recognize.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_RECOGNIZE_H
#define REALSENSE_PERSON_MESSAGE_RECOGNIZE_H

#include <ros/service_traits.h>


#include <realsense_person/RecognizeRequest.h>
#include <realsense_person/RecognizeResponse.h>


namespace realsense_person
{

struct Recognize
{

typedef RecognizeRequest Request;
typedef RecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Recognize
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::Recognize > {
  static const char* value()
  {
    return "7775c362719a4ed09f720639398479f1";
  }

  static const char* value(const ::realsense_person::Recognize&) { return value(); }
};

template<>
struct DataType< ::realsense_person::Recognize > {
  static const char* value()
  {
    return "realsense_person/Recognize";
  }

  static const char* value(const ::realsense_person::Recognize&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::RecognizeRequest> should match
// service_traits::MD5Sum< ::realsense_person::Recognize >
template<>
struct MD5Sum< ::realsense_person::RecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Recognize >::value();
  }
  static const char* value(const ::realsense_person::RecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::RecognizeRequest> should match
// service_traits::DataType< ::realsense_person::Recognize >
template<>
struct DataType< ::realsense_person::RecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Recognize >::value();
  }
  static const char* value(const ::realsense_person::RecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::RecognizeResponse> should match
// service_traits::MD5Sum< ::realsense_person::Recognize >
template<>
struct MD5Sum< ::realsense_person::RecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Recognize >::value();
  }
  static const char* value(const ::realsense_person::RecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::RecognizeResponse> should match
// service_traits::DataType< ::realsense_person::Recognize >
template<>
struct DataType< ::realsense_person::RecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Recognize >::value();
  }
  static const char* value(const ::realsense_person::RecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_RECOGNIZE_H
