// Generated by gencpp from file realsense_person/ReinforceRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_REINFORCEREQUEST_H
#define REALSENSE_PERSON_MESSAGE_REINFORCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_person
{
template <class ContainerAllocator>
struct ReinforceRequest_
{
  typedef ReinforceRequest_<ContainerAllocator> Type;

  ReinforceRequest_()
    : tracking_id(0)
    , recognition_id(0)  {
    }
  ReinforceRequest_(const ContainerAllocator& _alloc)
    : tracking_id(0)
    , recognition_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _tracking_id_type;
  _tracking_id_type tracking_id;

   typedef int32_t _recognition_id_type;
  _recognition_id_type recognition_id;





  typedef boost::shared_ptr< ::realsense_person::ReinforceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_person::ReinforceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReinforceRequest_

typedef ::realsense_person::ReinforceRequest_<std::allocator<void> > ReinforceRequest;

typedef boost::shared_ptr< ::realsense_person::ReinforceRequest > ReinforceRequestPtr;
typedef boost::shared_ptr< ::realsense_person::ReinforceRequest const> ReinforceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_person::ReinforceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_person::ReinforceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_person::ReinforceRequest_<ContainerAllocator1> & lhs, const ::realsense_person::ReinforceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tracking_id == rhs.tracking_id &&
    lhs.recognition_id == rhs.recognition_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_person::ReinforceRequest_<ContainerAllocator1> & lhs, const ::realsense_person::ReinforceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_person::ReinforceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::ReinforceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::ReinforceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d151849d51ed77fbb4d044d9d444cbc9";
  }

  static const char* value(const ::realsense_person::ReinforceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd151849d51ed77fbULL;
  static const uint64_t static_value2 = 0xb4d044d9d444cbc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_person/ReinforceRequest";
  }

  static const char* value(const ::realsense_person::ReinforceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 tracking_id\n"
"int32 recognition_id\n"
;
  }

  static const char* value(const ::realsense_person::ReinforceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tracking_id);
      stream.next(m.recognition_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReinforceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_person::ReinforceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_person::ReinforceRequest_<ContainerAllocator>& v)
  {
    s << indent << "tracking_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tracking_id);
    s << indent << "recognition_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.recognition_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_REINFORCEREQUEST_H
