// Generated by gencpp from file realsense_person/Reinforce.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_REINFORCE_H
#define REALSENSE_PERSON_MESSAGE_REINFORCE_H

#include <ros/service_traits.h>


#include <realsense_person/ReinforceRequest.h>
#include <realsense_person/ReinforceResponse.h>


namespace realsense_person
{

struct Reinforce
{

typedef ReinforceRequest Request;
typedef ReinforceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reinforce
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::Reinforce > {
  static const char* value()
  {
    return "2b7c244f8f3a54458eeafecb4a88c517";
  }

  static const char* value(const ::realsense_person::Reinforce&) { return value(); }
};

template<>
struct DataType< ::realsense_person::Reinforce > {
  static const char* value()
  {
    return "realsense_person/Reinforce";
  }

  static const char* value(const ::realsense_person::Reinforce&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::ReinforceRequest> should match
// service_traits::MD5Sum< ::realsense_person::Reinforce >
template<>
struct MD5Sum< ::realsense_person::ReinforceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Reinforce >::value();
  }
  static const char* value(const ::realsense_person::ReinforceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::ReinforceRequest> should match
// service_traits::DataType< ::realsense_person::Reinforce >
template<>
struct DataType< ::realsense_person::ReinforceRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Reinforce >::value();
  }
  static const char* value(const ::realsense_person::ReinforceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::ReinforceResponse> should match
// service_traits::MD5Sum< ::realsense_person::Reinforce >
template<>
struct MD5Sum< ::realsense_person::ReinforceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Reinforce >::value();
  }
  static const char* value(const ::realsense_person::ReinforceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::ReinforceResponse> should match
// service_traits::DataType< ::realsense_person::Reinforce >
template<>
struct DataType< ::realsense_person::ReinforceResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Reinforce >::value();
  }
  static const char* value(const ::realsense_person::ReinforceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_REINFORCE_H
