// Generated by gencpp from file realsense_person/Serialize.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_SERIALIZE_H
#define REALSENSE_PERSON_MESSAGE_SERIALIZE_H

#include <ros/service_traits.h>


#include <realsense_person/SerializeRequest.h>
#include <realsense_person/SerializeResponse.h>


namespace realsense_person
{

struct Serialize
{

typedef SerializeRequest Request;
typedef SerializeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Serialize
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::Serialize > {
  static const char* value()
  {
    return "f43a8e1b362b75baa741461b46adc7e0";
  }

  static const char* value(const ::realsense_person::Serialize&) { return value(); }
};

template<>
struct DataType< ::realsense_person::Serialize > {
  static const char* value()
  {
    return "realsense_person/Serialize";
  }

  static const char* value(const ::realsense_person::Serialize&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::SerializeRequest> should match
// service_traits::MD5Sum< ::realsense_person::Serialize >
template<>
struct MD5Sum< ::realsense_person::SerializeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Serialize >::value();
  }
  static const char* value(const ::realsense_person::SerializeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::SerializeRequest> should match
// service_traits::DataType< ::realsense_person::Serialize >
template<>
struct DataType< ::realsense_person::SerializeRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Serialize >::value();
  }
  static const char* value(const ::realsense_person::SerializeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::SerializeResponse> should match
// service_traits::MD5Sum< ::realsense_person::Serialize >
template<>
struct MD5Sum< ::realsense_person::SerializeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::Serialize >::value();
  }
  static const char* value(const ::realsense_person::SerializeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::SerializeResponse> should match
// service_traits::DataType< ::realsense_person::Serialize >
template<>
struct DataType< ::realsense_person::SerializeResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::Serialize >::value();
  }
  static const char* value(const ::realsense_person::SerializeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_SERIALIZE_H
