// Generated by gencpp from file realsense_person/StartTrackingResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_STARTTRACKINGRESPONSE_H
#define REALSENSE_PERSON_MESSAGE_STARTTRACKINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_person
{
template <class ContainerAllocator>
struct StartTrackingResponse_
{
  typedef StartTrackingResponse_<ContainerAllocator> Type;

  StartTrackingResponse_()
    : status(0)
    , status_desc()  {
    }
  StartTrackingResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , status_desc(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_desc_type;
  _status_desc_type status_desc;





  typedef boost::shared_ptr< ::realsense_person::StartTrackingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_person::StartTrackingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartTrackingResponse_

typedef ::realsense_person::StartTrackingResponse_<std::allocator<void> > StartTrackingResponse;

typedef boost::shared_ptr< ::realsense_person::StartTrackingResponse > StartTrackingResponsePtr;
typedef boost::shared_ptr< ::realsense_person::StartTrackingResponse const> StartTrackingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_person::StartTrackingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_person::StartTrackingResponse_<ContainerAllocator1> & lhs, const ::realsense_person::StartTrackingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.status_desc == rhs.status_desc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_person::StartTrackingResponse_<ContainerAllocator1> & lhs, const ::realsense_person::StartTrackingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_person::StartTrackingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::StartTrackingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::StartTrackingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbfa2262d85d80c0b56ce4d61f4542fd";
  }

  static const char* value(const ::realsense_person::StartTrackingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbfa2262d85d80c0ULL;
  static const uint64_t static_value2 = 0xb56ce4d61f4542fdULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_person/StartTrackingResponse";
  }

  static const char* value(const ::realsense_person::StartTrackingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string status_desc\n"
"\n"
"\n"
;
  }

  static const char* value(const ::realsense_person::StartTrackingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.status_desc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTrackingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_person::StartTrackingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_person::StartTrackingResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "status_desc: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_desc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_STARTTRACKINGRESPONSE_H
