// Generated by gencpp from file realsense_person/StopTracking.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_STOPTRACKING_H
#define REALSENSE_PERSON_MESSAGE_STOPTRACKING_H

#include <ros/service_traits.h>


#include <realsense_person/StopTrackingRequest.h>
#include <realsense_person/StopTrackingResponse.h>


namespace realsense_person
{

struct StopTracking
{

typedef StopTrackingRequest Request;
typedef StopTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopTracking
} // namespace realsense_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_person::StopTracking > {
  static const char* value()
  {
    return "dbfa2262d85d80c0b56ce4d61f4542fd";
  }

  static const char* value(const ::realsense_person::StopTracking&) { return value(); }
};

template<>
struct DataType< ::realsense_person::StopTracking > {
  static const char* value()
  {
    return "realsense_person/StopTracking";
  }

  static const char* value(const ::realsense_person::StopTracking&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_person::StopTrackingRequest> should match
// service_traits::MD5Sum< ::realsense_person::StopTracking >
template<>
struct MD5Sum< ::realsense_person::StopTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_person::StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::StopTrackingRequest> should match
// service_traits::DataType< ::realsense_person::StopTracking >
template<>
struct DataType< ::realsense_person::StopTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_person::StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_person::StopTrackingResponse> should match
// service_traits::MD5Sum< ::realsense_person::StopTracking >
template<>
struct MD5Sum< ::realsense_person::StopTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_person::StopTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_person::StopTrackingResponse> should match
// service_traits::DataType< ::realsense_person::StopTracking >
template<>
struct DataType< ::realsense_person::StopTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_person::StopTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_STOPTRACKING_H
