// Generated by gencpp from file realsense_person/StopTrackingRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_PERSON_MESSAGE_STOPTRACKINGREQUEST_H
#define REALSENSE_PERSON_MESSAGE_STOPTRACKINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_person
{
template <class ContainerAllocator>
struct StopTrackingRequest_
{
  typedef StopTrackingRequest_<ContainerAllocator> Type;

  StopTrackingRequest_()
    {
    }
  StopTrackingRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::realsense_person::StopTrackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_person::StopTrackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopTrackingRequest_

typedef ::realsense_person::StopTrackingRequest_<std::allocator<void> > StopTrackingRequest;

typedef boost::shared_ptr< ::realsense_person::StopTrackingRequest > StopTrackingRequestPtr;
typedef boost::shared_ptr< ::realsense_person::StopTrackingRequest const> StopTrackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_person::StopTrackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace realsense_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_person::StopTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_person::StopTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_person::StopTrackingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::realsense_person::StopTrackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_person/StopTrackingRequest";
  }

  static const char* value(const ::realsense_person::StopTrackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::realsense_person::StopTrackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopTrackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_person::StopTrackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::realsense_person::StopTrackingRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_PERSON_MESSAGE_STOPTRACKINGREQUEST_H
